{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-s7
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/S7_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/S7/S7_{{ version }}.tar.gz
  sha256: dce9613f389d3c49bf70e2dc57852b79b6e70474abb92887e13cb3d50d2a7b64

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('S7')"           # [not win]
    - "\"%R%\" -e \"library('S7')\""  # [win]

about:
  home: https://github.com/rconsortium/S7/, https://rconsortium.github.io/S7/
  license: MIT
  summary: A new object oriented programming system designed to be a successor to S3 and S4.
    It includes formal class, generic, and method specification, and a limited form
    of multiple dispatch. It has been designed and implemented collaboratively by the
    R Consortium Object-Oriented Programming Working Group, which includes representatives
    from R-Core, 'Bioconductor', 'Posit'/'tidyverse', and the wider R community.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: S7
# Title: An Object Oriented System Meant to Become a Successor to S3 and S4
# Version: 0.1.1
# Authors@R: c( person("Object-Oriented Programming Working Group", role = "cph"), person("Davis", "Vaughan", role = "aut"), person("Jim", "Hester", role = "aut", comment = c(ORCID = "0000-0002-2739-7082")), person("Tomasz", "Kalinowski", role = "aut"), person("Will", "Landau", role = "aut"), person("Michael", "Lawrence", role = "aut"), person("Martin", "Maechler", role = "aut", comment = c(ORCID = "0000-0002-8685-9910")), person("Luke", "Tierney", role = "aut"), person("Hadley", "Wickham", , "hadley@posit.co", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-4757-117X")) )
# Description: A new object oriented programming system designed to be a successor to S3 and S4. It includes formal class, generic, and method specification, and a limited form of multiple dispatch. It has been designed and implemented collaboratively by the R Consortium Object-Oriented Programming Working Group, which includes representatives from R-Core, 'Bioconductor', 'Posit'/'tidyverse', and the wider R community.
# License: MIT + file LICENSE
# URL: https://github.com/rconsortium/S7/, https://rconsortium.github.io/S7/
# BugReports: https://github.com/rconsortium/S7/issues
# Depends: R (>= 3.5.0)
# Imports: utils
# Suggests: bench, covr, knitr, methods, rmarkdown, testthat (>= 3.0.0), tibble
# VignetteBuilder: knitr
# Config/Needs/website: sloop
# Config/testthat/edition: 3
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# NeedsCompilation: yes
# Packaged: 2023-09-17 11:50:09 UTC; hadleywickham
# Author: Object-Oriented Programming Working Group [cph], Davis Vaughan [aut], Jim Hester [aut] (<https://orcid.org/0000-0002-2739-7082>), Tomasz Kalinowski [aut], Will Landau [aut], Michael Lawrence [aut], Martin Maechler [aut] (<https://orcid.org/0000-0002-8685-9910>), Luke Tierney [aut], Hadley Wickham [aut, cre] (<https://orcid.org/0000-0003-4757-117X>)
# Maintainer: Hadley Wickham <hadley@posit.co>
# Repository: CRAN
# Date/Publication: 2023-09-17 12:10:02 UTC
